name: .NET

on:
  push:
    branches:
      - master
      - web-service
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      working-directory: TwitchAchievementTrackerBackend
      run: dotnet restore ./TwitchAchievementTrackerBackend.sln
    - name: Build
      working-directory: TwitchAchievementTrackerBackend
      run: dotnet build --no-restore -p:ContinuousIntegrationBuild=true ./TwitchAchievementTrackerBackend.sln
    - name: Test
      working-directory: TwitchAchievementTrackerBackend
      run: dotnet test --no-build --verbosity normal ./TwitchAchievementTrackerBackend.sln

